### ISSUE TITLE
深拷贝与浅拷贝的问题

### ISSUE THREAD

**Issue by royss7** [JeffLi1993/java-core-learning-example#1]
请问，在CopyT.java中这两段代码有什么区别吗？
"""

```
    // 浅拷贝
    // 对其对象的引用却没有拷贝
    Student student2 = (Student) student1.clone();
    student2.setName("Jeff2");
    student2.getFamily().setName("Jeff2 Family");
    System.out.println(student1.getName() + " " + student1.getFamily().getName());
    System.out.println(student2.getName() + " " + student2.getFamily().getName());

    // 深拷贝
```

//        Student student2 = (Student) student1.clone();
//        student2.setName("Jeff2");
//        student2.getFamily().setName("Jeff2 Family");
//        System.out.println(student1.getName() + " " + student1.getFamily().getName());
//        System.out.println(student2.getName() + " " + student2.getFamily().getName());
"""

**Comment by hwlong** [comment]
同问，这是一样的代码啊！？

**Comment by JeffLi1993** [comment]
提 PR

**Comment by peierlong** [comment]
这两段代码一样啊
